### ISSUE TITLE
No to Licenses or Acknowledgements? No problem.

### ISSUE THREAD

**Issue by Surfboardv2ray** [SezarSec/SezarSec-Worker-Panel#2]
درود دوست عزیز، درسته فعالیت‌ها در یک راستا و برای یک هدف واحد هست، اما از نظر اخلاقی، خصوصا اگر با تجربه‌تر باشید که احتمالا هستید و با در نظر نگرفتن لایسنس که بر بستر این سرویس هست، این امر صدق میکنه که سازنده اسکریپت هم ذکر نشده نمونه. امیدواریم موفق باشید، در ضمن اسکریپت هم آپدیت شده، ویژگی جدید رو هم حتما اضافه کنین بهش :)

**Comment by SezarSec** [comment]
سلام به شما و عرض خسته نباشید . ذکر منبع متاسفانه توسط دوستانی که فایل readme رو نوشته بودند فراموش شده بود و از این بابت از شما عذرخواه هستیم منبع درج شد و ممنونیم از شما برای فعالیت در راستای اینترنت آزاد با آرزوی موفقیت .
